version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-service
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/evoting

  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  database:
    image: mongo:latest
    container_name: mongodb-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: